In [ ]:

# E-commerce Sales & Customer Analytics
# Step 1: Import Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")
print("E-commerce Analytics Project Started!")

Libraries imported successfully!
E-commerce Analytics Project Started!

In [ ]:
customers = pd.read_csv('/content/customers.csv')
orders = pd.read_csv('/content/orders.csv')
order_items = pd.read_csv('/content/order_items.csv')
products = pd.read_csv('/content/products.csv')

print("All CSV files loaded successfully!")

All CSV files loaded successfully!

In [ ]:

# Step 3: Check Dataset Dimensions

print("Customers Shape:", customers.shape)
print("Orders Shape:", orders.shape)
print("Order Items Shape:", order_items.shape)
print("Products Shape:", products.shape)

Customers Shape: (1000, 7)
Orders Shape: (5000, 5)
Order Items Shape: (8345, 8)
Products Shape: (41, 5)

In [ ]:

# Step 4.1: Display First 5 Rows

print("CUSTOMERS DATA")
display(customers.head())

print("ORDERS DATA")
display(orders.head())

print("ORDER ITEMS DATA")
display(order_items.head())

print("PRODUCTS DATA")
display(products.head())

CUSTOMERS DATA

,customer_id,customer_name,email,city,state,signup_date,customer_segment
0,C00001,Aditi Shinde,customer0001@example.com,Navi Mumbai,Maharashtra,2025-05-25,New
1,C00002,Pooja Mane,customer0002@example.com,Navi Mumbai,Maharashtra,2025-02-11,Premium
2,C00003,Sana Mane,customer0003@example.com,Kolhapur,Maharashtra,2025-06-09,Premium
3,C00004,Aarav Shah,customer0004@example.com,Amravati,Maharashtra,2026-02-23,New
4,C00005,Sneha Chavan,customer0005@example.com,Jalgaon,Maharashtra,2025-11-17,New

ORDERS DATA

  order_id customer_id  order_date    payment_method order_status
0  O000001      C00945  2026-02-28        Debit Card   Processing
1  O000002      C00247  2025-04-20  Cash on Delivery    Delivered
2  O000003      C00907  2025-08-13       Credit Card    Delivered
3  O000004      C00772  2025-11-29       Net Banking      Shipped
4  O000005      C00227  2025-01-11       Net Banking     Returned

ORDER ITEMS DATA

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,sales_amount,profit
0,OI0000001,O000001,P033,1,1425.50,0.10,1282.95,357.79
1,OI0000002,O000002,P021,1,2784.34,0.05,2645.12,523.05
2,OI0000003,O000002,P037,3,235.80,0.00,707.40,197.34
3,OI0000004,O000003,P017,1,947.13,0.15,805.06,287.71
4,OI0000005,O000004,P005,1,4948.14,0.10,4453.33,1815.31

PRODUCTS DATA

  product_id          product_name     category  unit_price  cost_price
0       P001        Wireless Mouse  Electronics         599      345.86
1       P002  Bluetooth Headphones  Electronics        1999     1330.49
2       P003           Smart Watch  Electronics        3499     2336.35
3       P004             USB-C Hub  Electronics        1299      971.39
4       P005          External SSD  Electronics        4599     2638.02

In [ ]:

# Step 4.2: Dataset Information

print("CUSTOMERS INFO")
customers.info()

print("\nORDERS INFO")
orders.info()

print("\nORDER ITEMS INFO")
order_items.info()

print("\nPRODUCTS INFO")
products.info()

CUSTOMERS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1000 non-null   object
 1   customer_name     1000 non-null   object
 2   email             1000 non-null   object
 3   city              1000 non-null   object
 4   state             1000 non-null   object
 5   signup_date       1000 non-null   object
 6   customer_segment  1000 non-null   object
dtypes: object(7)
memory usage: 54.8+ KB

ORDERS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        5000 non-null   object
 1   customer_id     5000 non-null   object
 2   order_date      5000 non-null   object
 3   payment_method  5000 non-null   object
 4   order_status    5000 non-null   object
dtypes: object(5)
memory usage: 195.4+ KB

ORDER ITEMS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8345 entries, 0 to 8344
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  8345 non-null   object
 1   order_id       8345 non-null   object
 2   product_id     8345 non-null   object
 3   quantity       8345 non-null   int64
 4   unit_price     8345 non-null   float64
 5   discount_pct   8345 non-null   float64
 6   sales_amount   8345 non-null   float64
 7   profit         8345 non-null   float64
dtypes: float64(4), int64(1), object(3)
memory usage: 521.7+ KB

PRODUCTS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    41 non-null     object
 1   product_name  41 non-null     object
 2   category      41 non-null     object
 3   unit_price    41 non-null     int64
 4   cost_price    41 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.7+ KB

In [ ]:

# Step 4.3: Statistical Summary

print("CUSTOMERS SUMMARY")
display(customers.describe(include='all'))

print("ORDERS SUMMARY")
display(orders.describe(include='all'))

print("ORDER ITEMS SUMMARY")
display(order_items.describe())

print("PRODUCTS SUMMARY")
display(products.describe(include='all'))

CUSTOMERS SUMMARY

,customer_id,customer_name,email,city,state,signup_date,customer_segment
count,1000,1000,1000,1000,1000,1000,1000
unique,1000,399,1000,14,1,608,3
top,C01000,Vedant More,customer1000@example.com,Mumbai,Maharashtra,2024-01-22,Regular
freq,1,8,1,87,1000,5,351

ORDERS SUMMARY

       order_id customer_id  order_date payment_method order_status
count      5000        5000        5000           5000         5000
unique     5000         996         652              5            5
top     O005000      C00409  2025-06-15    Credit Card    Delivered
freq          1          15          18           1033         2493

ORDER ITEMS SUMMARY

          quantity   unit_price  discount_pct  sales_amount        profit
count  8345.000000  8345.000000   8345.000000   8345.000000   8345.000000
mean      1.901378  1553.843523      0.082091   2711.920688    763.787600
std       1.073957  1348.928802      0.073914   3120.674498   1103.557405
min       1.000000   137.130000      0.000000    109.710000   -196.500000
25%       1.000000   580.590000      0.000000    771.670000    166.740000
50%       2.000000  1008.990000      0.050000   1664.810000    389.920000
75%       2.000000  2100.210000      0.150000   3473.340000    887.700000
max       5.000000  5936.880000      0.200000  28893.350000  13288.450000

PRODUCTS SUMMARY

       product_id    product_name     category   unit_price   cost_price
count          41              41           41    41.000000    41.000000
unique         41              41            8          NaN          NaN
top          P001  Wireless Mouse  Electronics          NaN          NaN
freq            1               1            8          NaN          NaN
mean          NaN             NaN          NaN  1541.195122  1016.152683
std           NaN             NaN          NaN  1362.689459   836.480868
min           NaN             NaN          NaN   149.000000   106.310000
25%           NaN             NaN          NaN   599.000000   364.360000
50%           NaN             NaN          NaN   999.000000   654.560000
75%           NaN             NaN          NaN  1999.000000  1469.630000
max           NaN             NaN          NaN  5499.000000  3120.980000

In [ ]:

# Step 5.1: Missing Values Check

print("Customers Missing Values:")
display(customers.isnull().sum())

print("Orders Missing Values:")
display(orders.isnull().sum())

print("Order Items Missing Values:")
display(order_items.isnull().sum())

print("Products Missing Values:")
display(products.isnull().sum())

Customers Missing Values:

customer_id         0
customer_name       0
email               0
city                0
state               0
signup_date         0
customer_segment    0
dtype: int64

Orders Missing Values:

order_id          0
customer_id       0
order_date        0
payment_method    0
order_status      0
dtype: int64

Order Items Missing Values:

order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
discount_pct     0
sales_amount     0
profit           0
dtype: int64

Products Missing Values:

product_id      0
product_name    0
category        0
unit_price      0
cost_price      0
dtype: int64

In [ ]:

# Step 5.2: Duplicate Records Check

print("Customers Duplicates:", customers.duplicated().sum())
print("Orders Duplicates:", orders.duplicated().sum())
print("Order Items Duplicates:", order_items.duplicated().sum())
print("Products Duplicates:", products.duplicated().sum())

Customers Duplicates: 0
Orders Duplicates: 0
Order Items Duplicates: 0
Products Duplicates: 0

In [ ]:

# Step 5.3: Check Data Types

print("Customers Data Types:")
print(customers.dtypes)

print("\nOrders Data Types:")
print(orders.dtypes)

print("\nOrder Items Data Types:")
print(order_items.dtypes)

print("\nProducts Data Types:")
print(products.dtypes)

Customers Data Types:
customer_id         object
customer_name       object
email               object
city                object
state               object
signup_date         object
customer_segment    object
dtype: object

Orders Data Types:
order_id          object
customer_id       object
order_date        object
payment_method    object
order_status      object
dtype: object

Order Items Data Types:
order_item_id     object
order_id          object
product_id        object
quantity           int64
unit_price       float64
discount_pct     float64
sales_amount     float64
profit           float64
dtype: object

Products Data Types:
product_id       object
product_name     object
category         object
unit_price        int64
cost_price      float64
dtype: object

In [ ]:

# Step 6.2: Validate Unique IDs

print("Unique Customer IDs:", customers['customer_id'].nunique())
print("Unique Order IDs:", orders['order_id'].nunique())
print("Unique Order Item IDs:", order_items['order_item_id'].nunique())
print("Unique Product IDs:", products['product_id'].nunique())

Unique Customer IDs: 1000
Unique Order IDs: 5000
Unique Order Item IDs: 8345
Unique Product IDs: 41

In [ ]:

# Step 6.3: Convert Date Columns

customers['signup_date'] = pd.to_datetime(customers['signup_date'])
orders['order_date'] = pd.to_datetime(orders['order_date'])

print("Date columns converted successfully!")

Date columns converted successfully!

In [ ]:
# Step 7: Feature Engineering

orders['year'] = orders['order_date'].dt.year
orders['month'] = orders['order_date'].dt.month
orders['month_name'] = orders['order_date'].dt.month_name()
orders['day'] = orders['order_date'].dt.day

display(orders.head())

,order_id,customer_id,order_date,payment_method,order_status,year,month,day,month_name
0,O000001,C00945,2026-02-28,Debit Card,Processing,2026,2,28,February
1,O000002,C00247,2025-04-20,Cash on Delivery,Delivered,2025,4,20,April
2,O000003,C00907,2025-08-13,Credit Card,Delivered,2025,8,13,August
3,O000004,C00772,2025-11-29,Net Banking,Shipped,2025,11,29,November
4,O000005,C00227,2025-01-11,Net Banking,Returned,2025,1,11,January

In [ ]:
# Step 8: Sales Summary

print("Total Sales:", order_items['sales_amount'].sum())
print("Total Profit:", order_items['profit'].sum())
print("Total Quantity Sold:", order_items['quantity'].sum())

Total Sales: 22630978.14
Total Profit: 6373807.5200000005
Total Quantity Sold: 15867

In [ ]:

# Step 9: Validate Relationships Between Datasets

invalid_customers = ~orders['customer_id'].isin(
    customers['customer_id']
)

invalid_orders = ~order_items['order_id'].isin(
    orders['order_id']
)

invalid_products = ~order_items['product_id'].isin(
    products['product_id']
)

print("Invalid Customer References:", invalid_customers.sum())
print("Invalid Order References:", invalid_orders.sum())
print("Invalid Product References:", invalid_products.sum())

Invalid Customer References: 0
Invalid Order References: 0
Invalid Product References: 0

In [ ]:
# Step 10 : Data Cleaning Summary

cleaning_summary = pd.DataFrame({
    'Check': [
        'Missing Values in Order Items',
        'Duplicate Rows in Order Items',
        'Invalid Customer References',
        'Invalid Order References',
        'Invalid Product References',
        'Negative Profit Records'
    ],
    'Result': [
        order_items.isnull().sum().sum(),
        order_items.duplicated().sum(),
        invalid_customers.sum(),
        invalid_orders.sum(),
        invalid_products.sum(),
        (order_items['profit'] < 0).sum()
    ]
})

print(cleaning_summary)

                           Check  Result
0  Missing Values in Order Items       0
1  Duplicate Rows in Order Items       0
2    Invalid Customer References       0
3       Invalid Order References       0
4     Invalid Product References       0
5        Negative Profit Records      32

Step 11: Category-wise Sales Analysis

Business Question:
Which product category generates the highest sales?

In [ ]:
category_data = pd.merge(order_items, products, on='product_id')

sales = category_data.groupby('category')['sales_amount'].sum()

print(sales.sort_values(ascending=False))

category
Electronics       5469410.64
Furniture         5051495.29
Home & Kitchen    3702522.81
Fashion           2876417.93
Footwear          2713983.70
Books             1407710.61
Fitness           1126701.25
Stationery         282735.91
Name: sales_amount, dtype: float64

**Business Insight:**

Electronics is the highest-selling category, generating total sales of ₹54,69,410.64. Furniture ranks second with sales of ₹50,51,495.29. Stationery has the lowest sales at ₹2,82,735.91.

**Recommendation:** The business can investigate why Electronics performs well and explore opportunities to improve Stationery sales.

Step 12: Category-wise Profit Analysis

Business Question: Which product category generates the highest profit?

In [ ]:
# Category-wise Profit Analysis

category_data = pd.merge(order_items, products, on='product_id')

profit = category_data.groupby('category')['profit'].sum()

print(profit.sort_values(ascending=False))

category
Furniture         1690475.50
Electronics       1631363.06
Home & Kitchen    1050810.69
Fashion            658926.53
Footwear           557007.11
Books              425086.17
Fitness            271946.85
Stationery          88191.61
Name: profit, dtype: float64

**Business Insight:**

Furniture generates the highest total profit of ₹16,90,475.50, followed by Electronics with ₹16,31,363.06. Stationery generates the lowest total profit of ₹88,191.61.

**Recommendation:** The business should analyze the reasons behind Furniture's strong profitability and identify opportunities to improve Stationery's performance.

Step 13: Monthly Sales Analysis

Business Question: Which month has the highest sales?

In [ ]:

# Monthly Sales Analysis

monthly_data = pd.merge(order_items, orders, on='order_id')

monthly_sales = monthly_data.groupby('month_name')['sales_amount'].sum()

print(monthly_sales.sort_values(ascending=False))

month_name
August       2355987.30
March        2212557.11
July         2206418.35
January      2177368.74
May          2114838.68
April        2056392.39
June         2035713.70
September    1981701.24
February     1826203.53
October      1576576.56
December     1046813.31
November     1040407.23
Name: sales_amount, dtype: float64

**Business Insight:**

August recorded the highest sales of ₹23,55,987.30, while November recorded the lowest sales of ₹10,40,407.23.

**Recommendation:** The business should investigate why sales were lower in November and explore ways to improve sales during that month.

Q4 — Top 5 Products by Sales

Business Question: Which 5 products generate the highest total sales?

In [ ]:
# Top 5 Products by Sales

product_sales = order_items.groupby('product_id')['sales_amount'].sum()

print(product_sales.sort_values(ascending=False).head(5))

product_id
P030    2074302.60
P024    1735286.39
P005    1491662.34
P031    1463878.77
P003    1281884.86
Name: sales_amount, dtype: float64

**Business Insight:**

The top 5 products based on total sales are P030, P024, P005, P031, and P003. Among these, P030 ranks first with total sales of ₹20,74,302.60, while P003 ranks fifth with total sales of ₹12,81,884.86.

**Recommendation:** The business should analyze the sales performance of these top 5 products and maintain sufficient stock to meet customer demand.

Q5: Top 5 Products by Profit

Business Question: Which are the top 5 products based on total profit?

In [ ]:
# Top 5 Products by Profit

product_profit = order_items.groupby('product_id')['profit'].sum()

print(product_profit.sort_values(ascending=False).head(5))

product_id
P030    794700.80
P005    570993.36
P024    568452.47
P031    461379.30
P003    345008.51
Name: profit, dtype: float64

**Business Insight:**

The top 5 products based on total profit are P030, P005, P024, P031, and P003. Product P030 generates the highest profit of ₹7,94,700.80, while P003 ranks fifth with a profit of ₹3,45,008.51.

**Recommendation:** The business should analyze the factors contributing to P030's high profitability and maintain sufficient stock of profitable products.

Q6 — Payment Method Analysis

Business Question: Which payment method is used most frequently by customers?

In [ ]:
# Payment Method Analysis

print(orders['payment_method'].value_counts())

payment_method
Credit Card         1033
UPI                 1020
Cash on Delivery     991
Debit Card           981
Net Banking          975
Name: count, dtype: int64

**Business Insight:**

Credit Card is the most frequently used payment method, with 1,033 orders, followed by UPI with 1,020 orders. Net Banking has the lowest count, with 975 orders. The difference between the most and least used payment methods is relatively small.

**Recommendation:** The business should continue supporting all five payment methods to provide customers with flexible payment options.

### Sales Analysis by Order Status

**Business Question:** How much sales value is associated with each order status?

**Objective:** To understand how sales value is distributed across delivered, shipped, returned, cancelled, and processing orders.

In [ ]:
# Sales by Order Status

sales_status = pd.merge(order_items,orders[['order_id', 'order_status']],on='order_id')

status_sales = sales_status.groupby('order_status')['sales_amount'].sum()

print(status_sales.sort_values(ascending=False))

order_status
Delivered     11220687.62
Shipped        2964798.95
Returned       2894016.80
Cancelled      2779567.15
Processing     2771907.62
Name: sales_amount, dtype: float64

### Business Insight

Delivered orders account for the highest sales value of ₹1,12,20,687.62. Returned orders account for ₹28,94,016.80, while cancelled orders account for ₹27,79,567.15.

### Recommendation

The business should investigate the reasons for returned and cancelled orders and review its order fulfilment process to identify opportunities for improvement.

**Note:** These figures represent sales values associated with each order status, not confirmed net revenue or actual financial losses.

Q8 — Customer Segment-wise Sales

Business Question: Which customer segment generates the highest sales?

In [ ]:
# Q8: Customer Segment-wise Sales

customer_orders = pd.merge(orders, customers, on='customer_id')

customer_sales = pd.merge(customer_orders, order_items, on='order_id')

segment_sales = customer_sales.groupby('customer_segment')['sales_amount'].sum()

print(segment_sales.sort_values(ascending=False))

customer_segment
Regular    8050600.93
New        7327124.41
Premium    7253252.80
Name: sales_amount, dtype: float64

**Business Insight:**

The Regular customer segment generates the highest sales of ₹80,50,600.93, followed by the New segment with ₹73,27,124.41. The Premium segment generates sales of ₹72,53,252.80.

**Recommendation:** The business should understand the purchasing behaviour of Regular customers and develop strategies to improve sales from New and Premium customers.

Q9 — City-wise Sales Analysis

Business Question: Which city generates the highest sales?

In [ ]:
# Q9: City-wise Sales

customer_orders = pd.merge(orders, customers, on='customer_id')

customer_sales = pd.merge(customer_orders, order_items, on='order_id')

city_sales = customer_sales.groupby('city')['sales_amount'].sum()

print(city_sales.sort_values(ascending=False))

city
Mumbai              1967549.86
Thane               1901410.46
Kolhapur            1857651.43
Amravati            1842300.60
Aurangabad          1775438.91
Jalgaon             1656389.18
Satara              1648689.26
Navi Mumbai         1641541.16
Nashik              1616625.58
Pimpri-Chinchwad    1541902.54
Pune                1326103.51
Nagpur              1320904.61
Sangli              1296856.71
Solapur             1237614.33
Name: sales_amount, dtype: float64

**Business Insight:**

Mumbai generates the highest sales of ₹19,67,549.86, followed by Thane with ₹19,01,410.46. Solapur has the lowest sales among the listed cities, at ₹12,37,614.33.

**Recommendation:** The business should analyze customer demand in Mumbai and Thane and explore opportunities to improve sales in Solapur.

In [ ]:
customers.to_csv("customers_cleaned.csv", index=False)
orders.to_csv("orders_cleaned.csv", index=False)
order_items.to_csv("order_items_cleaned.csv", index=False)
products.to_csv("products_cleaned.csv", index=False)

print("All cleaned CSV files saved successfully!")

All cleaned CSV files saved successfully!

In [ ]:
from google.colab import files

files.download("customers_cleaned.csv")
files.download("orders_cleaned.csv")
files.download("order_items_cleaned.csv")
files.download("products_cleaned.csv")

FileNotFoundError: Cannot find file: customers_cleaned.csv

# EDA Summary — E-commerce Sales & Customer Analytics

## 1. Key Findings

**Sales Analysis**
- Electronics generated the highest category-wise sales of ₹54,69,410.64.
- August recorded the highest monthly sales of ₹23,55,987.30.
- November recorded the lowest monthly sales of ₹10,40,407.23.
- Mumbai generated the highest city-wise sales of ₹19,67,549.86.

**Profit Analysis**
- Furniture generated the highest category-wise profit of ₹16,90,475.50.
- Product P030 ranked first in both sales (₹20,74,302.60) and profit (₹7,94,700.80).
- The dataset contains 32 negative-profit records that require further investigation.

**Customer Analysis**
- The Regular customer segment generated the highest sales of ₹80,50,600.93.
- Credit Card was the most frequently used payment method, with 1,033 orders.

**Order Analysis**
- Delivered was the most common order status, with 2,493 orders.
- There were 628 returned orders and 627 cancelled orders.

## 2. Business Problems Identified

- Monthly sales vary, with November showing the lowest sales.
- Stationery has the lowest category-wise sales and profit.
- Some order items have negative profit.
- Returns and cancellations may indicate opportunities to improve the customer experience.
- Sales performance varies across cities and customer segments.

## 3. Recommendations to Improve Sales

- Analyze low-sales months and plan targeted promotions and seasonal campaigns.
- Improve product visibility and marketing for low-performing categories such as Stationery.
- Use customer purchase patterns to recommend relevant products.
- Encourage repeat purchases through loyalty offers and personalized campaigns.
- Analyze city-wise demand and focus marketing efforts on areas with growth opportunities.

## 4. Recommendations to Improve Profit

- Investigate negative-profit records by checking product costs, selling prices, and discounts.
- Review discount strategies to ensure promotions remain profitable.
- Focus on products and categories with strong profit performance.
- Evaluate product costs and pricing before making price changes.
- Monitor sales and profit together rather than judging performance by sales alone.

## 5. Recommendations to Reduce Returns and Cancellations

- Investigate the reasons behind returned and cancelled orders.
- Review product descriptions, product quality, delivery issues, and customer complaints.
- Improve order tracking and communication with customers.
- Monitor return and cancellation rates regularly.

## 6. Conclusion

The EDA identified important patterns in sales, profit, products, customers, cities, and order statuses. These findings help highlight areas where the business can investigate problems and develop improvement strategies.

The next steps are SQL analysis, Power BI dashboard development, and tracking business performance using measurable KPIs.

**Note:** These recommendations are based on the current dataset. Actual improvements in sales or profit must be measured after implementing business actions.